# Generated by Django 5.0.6 on 2024-07-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_bookauthor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(through="book.BookAuthor", to="book.author"),
        ),
    ]
